### ISSUE TITLE
Link to module publishing instructions on web interface

### ISSUE THREAD

**Issue by hxrts** [cosmos/atlas#51]
Had to click around a bit to find the module [publishing](https://github.com/cosmos/atlas/blob/main/docs/publishing.md) docs. What do you think about linking directly on the top bar under the heading "Publish"?

**Comment by alexanderbez** [comment]
Sure thing.

I have the following in the readme:

> More information about the architecture, publishing and module configuration can be found under docs.

But I will add an explicit section :)

**Comment by hxrts** [comment]
Much appreciated!
