### ISSUE TITLE
README: focus on deploying of modules

### ISSUE THREAD

**Issue by marbar3778** [cosmos/atlas#57]
To allow people to get up quickly the `readme` should focus on deploying modules instead of both deploying modules and working on the product. The setup for running atlas server can live in a `devlopment.md` file.

**Comment by alexanderbez** [comment]
What do you mean by "deploying"? You mean publishing? There already is a section on that in the [README](https://github.com/cosmos/atlas#publishing) and an entire doc dedicated to it.

Note, [cargo](https://github.com/rust-lang/cargo) follows a similar structure. All relevant info live in their own respective doc(s).

**Comment by marbar3778** [comment]
Yes publishing sorry. 

oh okay then ignore. Was thinking how to better shed light on publishing. It seems to be enough.
