### ISSUE TITLE
docker deployment

### ISSUE THREAD

**Issue by marbar3778** [cosmos/atlas#59]
Right now the process involves installing atlas locally. We should allow people to use a docker image. 

I can look into helping on this.

**Comment by alexanderbez** [comment]
Sure thing! I mean, no one will really run it except me/whoever maintains atlas.cosmos.network, however, I still think having a docker image is a good idea. In fact, DigitalOcean App platform now allows you to do custom docker images. Before it didn't and that's why I didn't bother.

**Comment by marbar3778** [comment]
Oh, I meant for the atlas binary for publishing, but it may be the same docker image?

**Comment by alexanderbez** [comment]
Ohh, why is a docker image needed to publish?

**Comment by marbar3778** [comment]
To avoid the need to install atlas locally. In the publishing doc you specify the need to install it this is a way to avoid it. I like using docker for things more than downloading it locally. Personal preference

**Comment by alexanderbez** [comment]
Gotcha, yeah why not. Can you help out?
