### ISSUE TITLE
cut release

### ISSUE THREAD

**Issue by marbar3778** [cosmos/atlas#65]
In order for me to use the github action in this repo instead of the one in my repo we need to draft a release. 

Assigning @alexanderbez  because I'm not sure the release process here.

**Comment by alexanderbez** [comment]
@marbar3778 do you just need a point release? Do you mind waiting until I wrap up the node explorer work (another week)?

**Comment by marbar3778** [comment]
Yea, it's fine. Will continue using the action I have up from my repo till then.

**Comment by alexanderbez** [comment]
Thanks! I think I can get most of this wrapped up today.
