### ISSUE TITLE
unable to get nodeid

### ISSUE THREAD

**Issue by marbar3778** [cosmos/atlas#67]
I am unable to get nodeID from atlas node explorer. We should be able to click on the nodeID section to copy it to the clipboard. This will make the values usable. Right now, we are unable to use nodes on the node explorer to get the data. 

<img width="935" alt="Screenshot 2021-03-02 at 15 06 10" src="https://user-images.githubusercontent.com/24299864/109660250-8dbd4380-7b60-11eb-94f1-aa69849d020d.png">

**Comment by alexanderbez** [comment]
Great idea!

Here is what we can do. Add a `v-on:dblclick` to that column, where the event handler simply just copies it to the user's clipboard. Maybe we also display a modal for a few seconds saying `NodeID Copied!`.
