### ISSUE TITLE
Cannot update a published module

### ISSUE THREAD

**Issue by balasan** [cosmos/atlas#72]
I was unable to update `documentation` or `sdk_compat` after publishing.

Steps to reproduce:
 - publish module
 - update .toml file
 - publish again

Expected result: 
Updated module metadata on the website.

Actual result: 
The module says "Updated: a few seconds ago" but no updates are applied.

ex: https://atlas.cosmos.network/modules/4
.toml file: https://github.com/relevant-community/oracle/blob/main/x/oracle/atlas/config.toml

**Comment by alexanderbez** [comment]
Hi @balasan. When you attempted to update, did you bump the version? You have to bump the version to update those fields. Documentation and other fields are tied to a specific _version_.

**Comment by balasan** [comment]
Ah, got it.
It's working now.
